#!/bin/bash

path="."

if [ $# -lt 2 ] || [ $# -gt 3 ] 
then 
	echo -e "Usage: \n\tpn_prop PNML_FILE PNML_FILE [PROPERTY_LIST]"
else
	if [ $# -eq 3 ]
	then
		erl -pa "$path/ebin" -run pn_suite prop_preservation $path $1 $2 "$3" -noshell -s erlang halt
	else 
		erl -pa "$path/ebin" -run pn_suite prop_preservation $path $1 $2 -noshell -s erlang halt
	fi
fi

